/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlUsuarios;
import controlador.contador;
import controlador.modificarUsuarios;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import vista.administrador.inicioAdmin;

/**
 *
 * @author Rodry-Escritorio
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicioSesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textPass = new javax.swing.JPasswordField();
        CerrarBott = new javax.swing.JButton();
        ingresarBot = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInicioSesion.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        textUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });

        textPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPassActionPerformed(evt);
            }
        });

        CerrarBott.setText("Salir");
        CerrarBott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarBottActionPerformed(evt);
            }
        });

        ingresarBot.setText("Ingresar");
        ingresarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBotActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Inicio de Sesion");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelInicioSesionLayout = new javax.swing.GroupLayout(jPanelInicioSesion);
        jPanelInicioSesion.setLayout(jPanelInicioSesionLayout);
        jPanelInicioSesionLayout.setHorizontalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(textUsuario))
                    .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPass)))
                .addContainerGap())
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ingresarBot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarBott)
                .addGap(40, 40, 40))
        );
        jPanelInicioSesionLayout.setVerticalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarBot)
                    .addComponent(CerrarBott))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBotActionPerformed

        //Obtener texto de ususario
        String usuarioVist = textUsuario.getText();
        //System.out.println(usuario);
        //Obtener texto de contraseña
        String passVist = textPass.getText();
        //System.out.println(pass);

        //creamos un objeto usuario para dejar guardado lo introducido en el txtVista
        Usuario usu = new Usuario();
        usu.setUsuario(usuarioVist);
        usu.setPassword(passVist);

        //se arma la tabla con el constructor
        ControlUsuarios cu = new ControlUsuarios();

        //se carga la tabla segun lo pedido
        DefaultTableModel listausuario = cu.validarUsuario(usu);

        //se verifica que sea correcto el pass del usuario
        //contamos las columnas creadas, si es cero es q no existe el ussuario
        int nroFila = listausuario.getRowCount();
        if (nroFila == 0) {
            JOptionPane.showMessageDialog(this, "no hay usuario registrado");
        } else {
            if (listausuario.getValueAt(0, 2).toString().equals(usu.getPassword())) {
               // this.setVisible(false);
               // inicio ini = new inicio();
               // ini.setVisible(true);
               // ini.iniciatxt(listausuario);
               
               //condicion para iniciar en modo admin o usuaio comun
                if(listausuario.getValueAt(0, 4).toString().equals("admin")){
                    this.setVisible(false);
                    inicioAdmin iniAdm = new inicioAdmin();
                    iniAdm.setVisible(true);
                    iniAdm.cargar(listausuario);
                }else{
                     this.setVisible(false);
                     inicio ini = new inicio();
                     ini.setVisible(true);
                     ini.iniciatxt(listausuario);
                    
                }
                
            } else {
                //Crar clase estatica para contador 
                contador cont = new contador();
                System.out.println(contador.getContador());
                if (contador.getContador() >= 3) {
                    
                    String idcuenta = listausuario.getValueAt(0, 0).toString();
                    modificarUsuarios modUsu = new modificarUsuarios();
                    modUsu.modifBannedFalso(idcuenta);
                    JOptionPane.showMessageDialog(this, "Cuenta n°: "+ listausuario.getValueAt(0, 0).toString()+" bloqueada. Por favor Comunicarse con gestion" );
                    cerrarPrograma();
                }

                JOptionPane.showMessageDialog(this, "No coincide la contraseña");

            }
        }

    }//GEN-LAST:event_ingresarBotActionPerformed

    private void cerrarPrograma(){
        System.exit(0);
    }
    private void CerrarBottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarBottActionPerformed
        login inicio = (login) SwingUtilities.getWindowAncestor(jPanelInicioSesion);
        //inicio.setVisible(false);
        inicio.dispose();

    }//GEN-LAST:event_CerrarBottActionPerformed

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed

    }//GEN-LAST:event_textUsuarioActionPerformed

    private void textPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarBott;
    private javax.swing.JButton ingresarBot;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
